In [95]:
import cv2
import cv2.aruco as aruco
import math

def findAruco(img, marker_size=5, total_markers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco,f'DICT_{marker_size}X{marker_size}_{total_markers}')
    arucoDict = aruco.Dictionary_get(key)
    arucoParam = aruco.DetectorParameters_create()
    bbox, ids,_= aruco.detectMarkers(gray,arucoDict,parameters=arucoParam)
    counter =0
    # Changes from here
    for box in bbox:
        x1 = abs(box[0][0][0]-box[0][2][0])/2
        val = min(box[0][0][0],box[0][2][0])
        x_coordinate = x1+val
        x2 = abs(box[0][0][1]-box[0][2][1])/2
        val2 = min(box[0][0][1],box[0][2][1])
        y_coordinate = x2+val2
#         extract1  = bbox[0][0]
#         extract2  = bbox[0][1]
#         extx = (extract1[0]-extract2[0])/2
#         exty = (extract1[1]-extract2[1])/2
#         angle = math.atan2(exty, extx)
#         result = math.degrees(angle)
        extx = (box[0][0][0]-box[0][1][0])/2
        exty = (box[0][0][1]-box[0][1][1])/2
        angle = math.atan2(exty, extx)
        result = math.degrees(angle)
        if(result>0):
            result = int(180-result)
        else:
            result = int(-(180+result))
        #print(result)
        print(box[0])
        counter = counter+1
    #print(bbox)
    if draw:
        aruco.drawDetectedMarkers(img,bbox)
    
    return bbox,ids
    

VideoCap = False
cap = cv2.VideoCapture(0)

while(True):
    
    img = cv2.imread("aruco_1.png")
    bbox,ids=findAruco(img)
    cv2.imshow("img",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    break
   

[[181. 313.]
 [ 87. 284.]
 [113. 192.]
 [208. 220.]]
[[415. 171.]
 [493. 234.]
 [430. 311.]
 [352. 250.]]


In [69]:
import cv2
import cv2.aruco as aruco
import math
img = cv2.imread("aruco_0.png")

marker_size=5
total_markers=250
draw=True



gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
key = getattr(aruco,f'DICT_{marker_size}X{marker_size}_{total_markers}')
arucoDict = aruco.Dictionary_get(key)
arucoParam = aruco.DetectorParameters_create()
bbox, ids,_= aruco.detectMarkers(gray,arucoDict,parameters=arucoParam)
# Changes from here
for box in bbox:
#         extract1  = bbox[0][0]
#         extract2  = bbox[0][1]
#         extx = (extract1[0]-extract2[0])/2
#         exty = (extract1[1]-extract2[1])/2
#         angle = math.atan2(exty, extx)
#         result = math.degrees(angle)
    extx = (box[0][0][0]-box[0][1][0])/2
    exty = (box[0][0][1]-box[0][1][1])/2
    angle = math.atan2(exty, extx)
    result = math.degrees(angle)
    if(result>0):
        result = int(180-result)
    else:
        result = int(-(180+result))
    print(result)
    print("End of box")

-138
End of box
-152
End of box
41
End of box


In [16]:
import numpy as np
import cv2
from cv2 import aruco
import math
from pyzbar import pyzbar
image = cv2.imread('qr_0.png')
# find the barcodes in the image and decode each of the barcodes
barcodes = pyzbar.decode(image)
# loop over the detected barcodes
print(barcodes)
for barcode in barcodes:
    # extract the bounding box location of the barcode and draw the
    # bounding box surrounding the barcode on the image
    (x, y, w, h) = barcode.rect
    centerlis = []
    cv2.rectangle(image, (x, y), (x + w, y + h), (0, 0, 255), 2)
    # the barcode data is a bytes object so if we want to draw it on
    # our output image we need to convert it to a string first
    barcodeData = barcode.data.decode("utf-8")
    barcodeType = barcode.type
    # draw the barcode data and barcode type on the image
#     text = "{} ({})".format(barcodeData, barcodeType)
#     cv2.putText(image, text, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX,
#         0.5, (0, 0, 255), 2)
#     l,t,w,h = barcode.rect
#     center = (w/2, h/2)
#     print(center)
    centerx = x+w/2
    centery = y+h/2
    centerlis.append(centerx)
    centerlis.append(centery)
    print(barcodeData)
    # print the barcode type and data to the terminal
    print("[INFO] Found {} barcode: {}".format(barcodeType, barcodeData))
# show the output image
cv2.imshow("Image", image)
cv2.waitKey(0)
cv2.destroyAllWindows()

[Decoded(data=b'F5', type='QRCODE', rect=Rect(left=600, top=108, width=367, height=365), polygon=[Point(x=600, y=435), Point(x=926, y=473), Point(x=967, y=147), Point(x=638, y=108)], quality=1, orientation='UP'), Decoded(data=b'D6', type='QRCODE', rect=Rect(left=116, top=67, width=348, height=346), polygon=[Point(x=116, y=83), Point(x=129, y=413), Point(x=464, y=395), Point(x=448, y=67)], quality=1, orientation='UP')]
F5
[INFO] Found QRCODE barcode: F5
D6
[INFO] Found QRCODE barcode: D6


In [18]:
import cv2
import numpy as np

# Load image, grayscale, median blur, sharpen image
image = ~cv2.imread('aruco_1.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blur = cv2.medianBlur(gray, 5)
sharpen_kernel = np.array([[-1,-1,-1], [-1,9,-1], [-1,-1,-1]])
sharpen = cv2.filter2D(blur, -1, sharpen_kernel)

# Threshold and morph close
thresh = cv2.threshold(sharpen, 200, 500, cv2.THRESH_BINARY_INV)[1]
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3,3))
close = cv2.morphologyEx(thresh, cv2.MORPH_CLOSE, kernel, iterations=2)

# Find contours and filter using threshold area
contours = cv2.findContours(~close, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
contours = contours[0] if len(contours) == 2 else contours[1]

result1 = image.copy()
result2 = image.copy()
for c in contours:
    cv2.drawContours(result1,[c],0,(0,0,0),2)
    # get rotated rectangle from contour
    rot_rect = cv2.minAreaRect(c)
    #print(rot_rect)
    box = cv2.boxPoints(rot_rect)
    print(rot_rect)
    box = np.int0(box)
    
    # draw rotated rectangle on copy of img
    cv2.drawContours(result2,[box],0,(0,0,0),2)
cv2.imshow("thresh", thresh)
cv2.imshow("clean", close)
cv2.imshow("result1", result1)
cv2.imshow("result2", result2)
cv2.waitKey(0)
cv2.destroyAllWindows()

((4.5, 474.0), (10.0, 9.0), 90.0)
((147.27064514160156, 252.43121337890625), (99.61393737792969, 97.98563385009766), 16.699243545532227)
((422.1390380859375, 241.94589233398438), (100.30159759521484, 101.59701538085938), 38.990997314453125)


In [2]:
import cv2
import cv2.aruco as aruco

def findAruco(img, marker_size=5, total_markers=250, draw=True):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    key = getattr(aruco,f'DICT_{marker_size}X{marker_size}_{total_markers}')
    arucoDict = aruco.Dictionary_get(key)
    arucoParam = aruco.DetectorParameters_create()
    bbox, ids,_= aruco.detectMarkers(gray,arucoDict,parameters=arucoParam)
    print(bbox)
    if draw:
        aruco.drawDetectedMarkers(img,bbox)
    if len(bbox) > 0:
        for i in range(0, len(ids)):
            # Estimate pose of each marker and return the values rvec and tvec---(different from those of camera coefficients)
            rvec, tvec, markerPoints = cv2.aruco.estimatePoseSingleMarkers(bbox[i], 0.02)
            # Draw a square around the markers
            cv2.aruco.drawDetectedMarkers(frame, bbox) 

            # Draw Axis
            cv2.aruco.drawAxis(frame, None, None, rvec, tvec, 0.01)
    
    return bbox,ids

    

VideoCap = False
cap = cv2.VideoCapture(0)

while(True):
    
    img = cv2.imread("aruco_0.png")
    bbox,ids=findAruco(img)
    cv2.imshow("img",img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    break
   

(array([[[327., 331.],
        [255., 395.],
        [189., 325.],
        [260., 259.]]], dtype=float32), array([[[541., 155.],
        [451., 201.],
        [406., 110.],
        [496.,  64.]]], dtype=float32), array([[[ 61., 123.],
        [129.,  62.],
        [190., 130.],
        [121., 191.]]], dtype=float32))


error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'estimatePoseSingleMarkers'
> Overload resolution failed:
>  - estimatePoseSingleMarkers() missing required argument 'cameraMatrix' (pos 3)
>  - estimatePoseSingleMarkers() missing required argument 'cameraMatrix' (pos 3)
